version: 2.1
orbs:
  slack: circleci/slack@4.4.0


jobs: 
  build1:
    docker: 
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: echo "hello junip"  
  build2:
    docker:
      - image: 'cimg/python:3.6'      
    steps:
      - checkout
      - run:
          name: "second build command"
          command: |
            echo "asdasd"
            echo "asdasd333"
  build3:
    docker:
      - image: 'cimg/python:3.6'      
    steps:
      - checkout
      - run:
          name: "third build command"
          command: |
            echo "third build running"
            echo "third build message printed"
  build4:
    docker:
      - image: 'cimg/python:3.6'      
    steps:
      - checkout
      - run:
          name: "fourth build command"
          command: |
            echo "fourth build running"
            echo "fourth build message printed"   
  build5:
    docker:
      - image: 'cimg/python:3.6'      
    steps:
      - checkout
      - run:
          name: "fifth build command"
          command: |
            echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV
      - run:
          name: "What branch am I on now?"
          command: echo ${MY_ENV_VAR}     
  build6: 
    docker:
      - image: 'cimg/python:3.6' 
    steps:
      - checkout
      - run:
          name: "executing sixth command"
          command: |
            var approver=curl -s --request GET 'https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/job' \
            --header "circle-token: $CIRCLECI_TOKEN" \
            --header 'content-type: application/json' | jq '.items | .[] | select(.type == "approval") | {approved_by}'               
            echo 'export BUILD_APPROVER=${approver}' >> $BASH_ENV
  build7:
    docker:
      - image: 'cimg/python:3.6' 
    steps:
      - run:  echo ${BUILD_APPROVER}        
  notification_on_slack:
    docker:
      - image: 'cimg/python:3.6' 
    steps:
      - run:
          name: 'slack notifications'
          command: | 
            echo "Import Map before deployment:"
            echo " $(myName)"
          run: echo " ${BUILD_APPROVER}"
      - slack/notify:
          channel: C01VBGM6DM0
          event: pass
          template: success_tagged_deploy_1

      - slack/notify:
          channel: C01VBGM6DM0
          event: pass
          custom: |
            { 
              "text": "CircleCI job succeeded!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*:rocket: Deployment Successful!*"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Project*:\n$CIRCLE_PROJECT_REPONAME"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Branch*: $CIRCLE_BRANCH"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Commit*: $CIRCLE_SHA1"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Author*: $CIRCLE_USERNAME"
                    }
                  ],
                  "accessory": {
                    "type": "image",
                    "image_url": "https://w7.pngwing.com/pngs/814/561/png-transparent-brown-and-white-rocket-illustration-kennedy-space-center-space-shuttle-program-sts-129-international-space-station-space-shuttle-atlantis-rockets-spacecraft-rocket-launch-nasa.png",
                    "alt_text": "CircleCI logo"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Job"
                      },
                      "url": "${CIRCLE_BUILD_URL}"
                    }
                  ]
                }
              ]
            }
         

workflows:
  version: 2
  test_and_deploy: 
    jobs:
      - build1
      - build2: 
          requires: 
            - build1
      - build3: 
          requires: 
            - build1
      - build4: 
          requires: 
            - build1
      - build5: 
          requires: 
            - build2
            - build3
            - build4
      - build6:
          type: approval
          requires:
            - build5
      - notification_on_slack:
          requires: 
            - build6