version: 2

jobs: 
  build1:
    docker: 
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: echo "hello junip"  
  build2:
    docker:
      - image: 'cimg/python:3.6'      
    steps:
      - checkout
      - run:
          name: "second build command"
          command: |
            echo "asdasd"
            echo "asdasd333"
        

workflows:
  version: 2
  test_and_deploy: 
    jobs:
      - build1
      - build2: 
          requires: 
            - build1